# Generated by Django 4.1.3 on 2022-12-07 10:02

from django.db import migrations, models
import petstagram.validators


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="photo",
            field=models.ImageField(
                upload_to="pet_photos/",
                validators=[petstagram.validators.MaxSizeValidator(5)],
            ),
        ),
    ]
