# Generated by Django 4.1.3 on 2023-07-18 05:32

import django.core.validators
from django.db import migrations, models
import petstagram.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), petstagram.validators.string_is_alpha]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), petstagram.validators.string_is_alpha], verbose_name='last name'),
        ),
    ]
