# Generated by Django 4.1.3 on 2022-12-01 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "related_photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="photos.photo"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhotoComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment_publish_date_time",
                    models.DateTimeField(auto_created=True, auto_now_add=True),
                ),
                ("comment_text", models.CharField(max_length=300)),
                (
                    "related_photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="photos.photo"
                    ),
                ),
            ],
        ),
    ]
