# Generated by Django 4.1.3 on 2022-12-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photocomment", options={"ordering": ["-comment_publish_date_time"]},
        ),
    ]
