# Generated by Django 4.1.3 on 2022-12-01 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("pet_photo", models.URLField()),
                ("pet_birth_date", models.DateField(blank=True, null=True)),
                ("pet_slug", models.SlugField(blank=True, editable=False, unique=True)),
            ],
        ),
    ]
